-- CreateEnum
CREATE TYPE "MeadSubtype" AS ENUM ('ACERGLYN', 'BRAGGOT', 'BOCHET', 'CAPSICUMEL', 'CYSER', 'SACK_MEAD', 'HIPPOCRAS', 'HYDROMEL', 'METHEGLIN', 'MORAT', 'MELOMEL', 'MULLED_MEAD', 'OMPHACOMEL', 'OXYMEL', 'PYMENT', 'RHODOMEL', 'SHORT_MEAD', 'SHOW_MEAD', 'SPARKLING_MEAD', 'SOUR_MEAD');

-- AlterTable
ALTER TABLE "Batch" ADD COLUMN     "meadSubtype" "MeadSubtype";
